[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Allow Netlify to ignore public Firebase keys (AIzaâ€¦)
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "true"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIza"
